# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30)),
                ('iban', models.CharField(max_length=22)),
                ('bic', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course title', models.CharField(max_length=20)),
                ('autoBill', models.BooleanField(verbose_name='Shall this course be auto-billed?')),
                ('beginTime', models.DateTimeField(verbose_name='Starting time of the course')),
                ('endTime', models.DateTimeField(verbose_name='End time of the course')),
                ('beginDate', models.DateField(verbose_name='Start date of the course')),
                ('endDate', models.DateField(verbose_name='End date of the course')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer name', models.CharField(max_length=30)),
                ('SEPAvalid', models.BooleanField(verbose_name='Is the SEPA valid?')),
                ('address', models.CharField(max_length=30)),
                ('Account which pays for courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billGenerator.Account')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billGenerator.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('dateFirstAid', models.DateField(verbose_name='latest first aid certificate')),
                ('Account to pay to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billGenerator.Account')),
                ('Courses given by trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billGenerator.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billGenerator.Customer'),
        ),
        migrations.AddField(
            model_name='course',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billGenerator.Trainer'),
        ),
    ]
