# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billGenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='weekday of the session',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
