# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billGenerator', '0002_course_weekday of the session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Braunschweig', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='extra to the house number',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='house number',
            field=models.IntegerField(default=34),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal code',
            field=models.IntegerField(default=38106),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(default='Franz-Liszt-Straße', max_length=30),
        ),
        migrations.AddField(
            model_name='trainer',
            name='city',
            field=models.CharField(default='Braunschweig', max_length=20),
        ),
        migrations.AddField(
            model_name='trainer',
            name='extra to the house number',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='trainer',
            name='house number',
            field=models.IntegerField(default=34),
        ),
        migrations.AddField(
            model_name='trainer',
            name='postal code',
            field=models.IntegerField(default=38106),
        ),
        migrations.AddField(
            model_name='trainer',
            name='street',
            field=models.CharField(default='Franz-Liszt-Straße', max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='customers',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='billGenerator.Customer'),
        ),
        migrations.AlterField(
            model_name='course',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='billGenerator.Trainer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='courses',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='billGenerator.Course'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Courses given by trainer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='billGenerator.Course'),
        ),
    ]
