# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billGenerator', '0003_auto_20170414_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billGenerator.Course'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Courses given by trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billGenerator.Course'),
        ),
    ]
