# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billGenerator', '0004_auto_20170414_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Customer name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='Customer name',
            new_name='name',
        ),
    ]
