# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 20:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billGenerator', '0005_auto_20170414_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='beginTime',
            field=models.TimeField(verbose_name='Starting time of the course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='endTime',
            field=models.TimeField(verbose_name='End time of the course'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='dateFirstAid',
            field=models.DateField(default=datetime.date(2017, 4, 14), verbose_name='latest first aid certificate'),
        ),
    ]
