# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billGenerator', '0007_auto_20170414_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='dateFirstAid',
            field=models.DateField(verbose_name='latest first aid certificate'),
        ),
    ]
