# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billGenerator', '0009_auto_20170414_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Course title',
            new_name='title',
        ),
    ]
