# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billGenerator', '0010_auto_20170414_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='weekday of the session',
            new_name='dayOfWeek',
        ),
    ]
